AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Capital Wealth Management – Serverless API (Production)

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment

Globals:
  Function:
    Timeout: 15                # Production-appropriate
    MemorySize: 512            # Increased for realistic workloads
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Tags:
        project: capital-wealth
        environment: !Ref Environment

Outputs:

  ApiBaseUrl:
    Description: Base API Gateway URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"

  HelloWorldEndpoint:
    Description: Hello World endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"

  HelloWorldFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
